import { log } from "./audit.registry";
import type { AuditEventInput } from "./audit.types";

const baseContext = {
  userId: "user-admin",
  workspaceId: "workspace-main",
  companyId: "company-hicotech",
  ip: "196.75.24.18",
  device: "MacBook Pro",
  browser: "Chrome",
  platform: "macOS",
  sessionId: "session-demo-admin",
  correlationId: "corr-demo-2026-06-29"
};

export const demoAuditEvents: AuditEventInput[] = [
  {
    ...baseContext,
    id: "audit-admin-login",
    timestamp: "2026-06-29T09:00:00.000Z",
    action: "login",
    category: "authentication",
    severity: "success",
    message: "Admin login successful",
    entityType: "user",
    entityId: "user-admin",
    moduleId: "users",
    duration: 184
  },
  {
    ...baseContext,
    id: "audit-invoice-created",
    timestamp: "2026-06-29T09:14:00.000Z",
    action: "create",
    category: "sales",
    severity: "success",
    message: "Invoice F-2026-154 created",
    entityType: "invoice",
    entityId: "F-2026-154",
    moduleId: "invoices",
    details: { amount: 12500, customer: "ABC SARL" },
    duration: 320
  },
  {
    ...baseContext,
    id: "audit-invoice-updated",
    timestamp: "2026-06-29T09:18:00.000Z",
    action: "update",
    category: "sales",
    severity: "info",
    message: "Invoice F-2026-154 updated",
    entityType: "invoice",
    entityId: "F-2026-154",
    moduleId: "invoices",
    details: { field: "dueDate" },
    duration: 210
  },
  {
    ...baseContext,
    id: "audit-invoice-printed",
    timestamp: "2026-06-29T09:20:00.000Z",
    action: "print",
    category: "documents",
    severity: "info",
    message: "Invoice F-2026-154 printed",
    entityType: "invoice",
    entityId: "F-2026-154",
    moduleId: "pdf",
    duration: 540
  },
  {
    ...baseContext,
    id: "audit-quote-converted",
    timestamp: "2026-06-29T09:24:00.000Z",
    action: "execute",
    category: "sales",
    severity: "success",
    message: "Quote Q-2026-088 converted to invoice",
    entityType: "quote",
    entityId: "Q-2026-088",
    moduleId: "quotes",
    metadata: { targetInvoice: "F-2026-154" },
    duration: 410
  },
  {
    ...baseContext,
    id: "audit-payment-received",
    timestamp: "2026-06-29T09:30:00.000Z",
    action: "create",
    category: "finance",
    severity: "success",
    message: "Payment received from ABC SARL",
    entityType: "payment",
    entityId: "PAY-2026-044",
    moduleId: "payments",
    details: { amount: 12500, method: "bank_transfer" },
    duration: 260
  },
  {
    ...baseContext,
    id: "audit-stock-updated",
    timestamp: "2026-06-29T09:36:00.000Z",
    action: "update",
    category: "inventory",
    severity: "info",
    message: "Stock updated for Interactive Screen 86",
    entityType: "product",
    entityId: "PROD-SCREEN-86",
    moduleId: "products",
    details: { previousQuantity: 4, nextQuantity: 2 },
    duration: 198
  },
  {
    ...baseContext,
    id: "audit-product-imported",
    timestamp: "2026-06-29T09:42:00.000Z",
    action: "import",
    category: "inventory",
    severity: "success",
    message: "Product import completed",
    entityType: "product_import",
    entityId: "IMPORT-2026-010",
    moduleId: "products",
    details: { imported: 42, updated: 6, skipped: 1 },
    duration: 2600
  },
  {
    ...baseContext,
    id: "audit-client-modified",
    timestamp: "2026-06-29T09:48:00.000Z",
    action: "update",
    category: "crm",
    severity: "info",
    message: "Client ABC SARL modified",
    entityType: "client",
    entityId: "client-abc-sarl",
    moduleId: "clients",
    details: { field: "phone" },
    duration: 170
  },
  {
    ...baseContext,
    id: "audit-ai-recommendation-executed",
    timestamp: "2026-06-29T10:00:00.000Z",
    action: "ai",
    category: "ai",
    severity: "success",
    message: "AI recommendation accepted for invoice reminder",
    entityType: "ai_recommendation",
    entityId: "AI-REC-2026-032",
    moduleId: "ai_assistant",
    details: { recommendation: "invoice_reminder", customer: "ABC SARL" },
    duration: 880
  },
  {
    ...baseContext,
    id: "audit-notification-archived",
    timestamp: "2026-06-29T10:06:00.000Z",
    action: "archive",
    category: "notifications",
    severity: "info",
    message: "Stock critical notification archived",
    entityType: "notification",
    entityId: "demo-critical-stock",
    moduleId: "dashboard",
    duration: 95
  },
  {
    ...baseContext,
    id: "audit-role-changed",
    timestamp: "2026-06-29T10:12:00.000Z",
    action: "update",
    category: "users",
    severity: "warning",
    message: "User role changed",
    entityType: "user",
    entityId: "user-stock",
    moduleId: "users",
    details: { previousRole: "READ_ONLY", nextRole: "STOCK_MANAGER" },
    duration: 230
  },
  {
    ...baseContext,
    id: "audit-backup-started",
    timestamp: "2026-06-29T10:20:00.000Z",
    action: "execute",
    category: "system",
    severity: "info",
    message: "Monthly backup started",
    entityType: "backup",
    entityId: "BACKUP-2026-06",
    moduleId: "settings",
    duration: 50
  },
  {
    ...baseContext,
    id: "audit-backup-completed",
    timestamp: "2026-06-29T10:24:00.000Z",
    action: "sync",
    category: "system",
    severity: "success",
    message: "Monthly backup completed",
    entityType: "backup",
    entityId: "BACKUP-2026-06",
    moduleId: "settings",
    duration: 240000
  },
  {
    ...baseContext,
    id: "audit-export-excel",
    timestamp: "2026-06-29T10:30:00.000Z",
    action: "export",
    category: "documents",
    severity: "info",
    message: "Products exported to Excel",
    entityType: "export",
    entityId: "EXPORT-XLSX-2026-011",
    moduleId: "products",
    details: { format: "xlsx", rows: 256 },
    duration: 1420
  },
  {
    ...baseContext,
    id: "audit-export-pdf",
    timestamp: "2026-06-29T10:34:00.000Z",
    action: "export",
    category: "documents",
    severity: "info",
    message: "Invoice PDF exported",
    entityType: "invoice",
    entityId: "F-2026-154",
    moduleId: "pdf",
    details: { format: "pdf" },
    duration: 900
  },
  {
    ...baseContext,
    id: "audit-settings-updated",
    timestamp: "2026-06-29T10:40:00.000Z",
    action: "update",
    category: "settings",
    severity: "warning",
    message: "Company PDF settings updated",
    entityType: "settings",
    entityId: "pdf-settings",
    moduleId: "settings",
    details: { field: "showStamp" },
    duration: 190
  },
  {
    ...baseContext,
    id: "audit-theme-changed",
    timestamp: "2026-06-29T10:45:00.000Z",
    action: "update",
    category: "settings",
    severity: "info",
    message: "Theme preference changed",
    entityType: "preference",
    entityId: "theme",
    moduleId: "settings",
    details: { value: "dark" },
    duration: 60
  },
  {
    ...baseContext,
    id: "audit-widget-reordered",
    timestamp: "2026-06-29T10:50:00.000Z",
    action: "update",
    category: "settings",
    severity: "info",
    message: "Dashboard widget order changed",
    entityType: "widget",
    entityId: "widget-business-health",
    moduleId: "dashboard",
    details: { area: "dashboard", order: 1 },
    duration: 75
  },
  {
    ...baseContext,
    id: "audit-supplier-created",
    timestamp: "2026-06-29T10:56:00.000Z",
    action: "create",
    category: "finance",
    severity: "success",
    message: "Supplier LG added",
    entityType: "supplier",
    entityId: "supplier-lg",
    moduleId: "suppliers",
    duration: 240
  },
  {
    ...baseContext,
    id: "audit-purchase-approved",
    timestamp: "2026-06-29T11:02:00.000Z",
    action: "approve",
    category: "finance",
    severity: "success",
    message: "Purchase PO-2026-19 approved",
    entityType: "purchase",
    entityId: "PO-2026-19",
    moduleId: "purchases",
    duration: 350
  },
  {
    ...baseContext,
    id: "audit-delivery-note-viewed",
    timestamp: "2026-06-29T11:08:00.000Z",
    action: "view",
    category: "sales",
    severity: "info",
    message: "Delivery note BL-2026-45 viewed",
    entityType: "delivery_note",
    entityId: "BL-2026-45",
    moduleId: "delivery_notes",
    duration: 45
  },
  {
    ...baseContext,
    id: "audit-employee-created",
    timestamp: "2026-06-29T11:14:00.000Z",
    action: "create",
    category: "users",
    severity: "success",
    message: "Employee Ahmed created",
    entityType: "employee",
    entityId: "employee-ahmed",
    moduleId: "employees",
    duration: 280
  },
  {
    ...baseContext,
    id: "audit-contract-updated",
    timestamp: "2026-06-29T11:20:00.000Z",
    action: "update",
    category: "users",
    severity: "info",
    message: "Employee contract renewed",
    entityType: "contract",
    entityId: "contract-ahmed-2026",
    moduleId: "contracts",
    duration: 260
  },
  {
    ...baseContext,
    id: "audit-payroll-exported",
    timestamp: "2026-06-29T11:26:00.000Z",
    action: "export",
    category: "documents",
    severity: "info",
    message: "Payroll report exported",
    entityType: "payroll",
    entityId: "PAYROLL-2026-06",
    moduleId: "payroll",
    duration: 1300
  },
  {
    ...baseContext,
    id: "audit-failed-login",
    timestamp: "2026-06-29T11:32:00.000Z",
    action: "login",
    category: "security",
    severity: "error",
    status: "failed",
    success: false,
    message: "Failed login attempt",
    entityType: "user",
    entityId: "stock@hicotech.ma",
    moduleId: "users",
    details: { reason: "invalid_password" },
    duration: 120
  },
  {
    ...baseContext,
    id: "audit-permission-rejected",
    timestamp: "2026-06-29T11:38:00.000Z",
    action: "reject",
    category: "security",
    severity: "warning",
    status: "blocked",
    success: false,
    message: "Permission change rejected",
    entityType: "permission",
    entityId: "role-sales-delete-invoice",
    moduleId: "users",
    details: { reason: "insufficient_scope" },
    duration: 160
  },
  {
    ...baseContext,
    id: "audit-document-restored",
    timestamp: "2026-06-29T11:44:00.000Z",
    action: "restore",
    category: "documents",
    severity: "success",
    message: "Archived document restored",
    entityType: "document",
    entityId: "DOC-2026-071",
    moduleId: "documents",
    duration: 210
  },
  {
    ...baseContext,
    id: "audit-module-sync",
    timestamp: "2026-06-29T11:50:00.000Z",
    action: "sync",
    category: "system",
    severity: "success",
    message: "Core modules synchronized",
    entityType: "core_registry",
    entityId: "core-modules",
    moduleId: "settings",
    duration: 480
  },
  {
    ...baseContext,
    id: "audit-custom-workflow",
    timestamp: "2026-06-29T11:56:00.000Z",
    action: "custom",
    category: "system",
    severity: "info",
    message: "Custom workflow placeholder executed",
    entityType: "workflow",
    entityId: "workflow-demo",
    moduleId: "dashboard",
    duration: 300
  }
];

demoAuditEvents.forEach(log);
