import type { HicoPilotWorkspace } from "./workspace.types";

const now = "2026-06-30T09:00:00.000Z";

export const demoWorkspaces: HicoPilotWorkspace[] = [
  {
    id: "workspace-main",
    name: "Executive Workspace",
    description: "Daily command center for business owners and administrators.",
    type: "executive",
    ownerId: "user-admin",
    companyId: "company-hicotech",
    defaultRoute: "/dashboard",
    modules: ["dashboard", "statistics", "reports", "cash", "payments", "invoices", "products", "clients", "ai_assistant"],
    widgets: [
      "widget-business-health",
      "widget-quick-actions",
      "widget-smart-insights",
      "widget-todays-priorities",
      "widget-recent-activity",
      "widget-my-tasks",
      "widget-system-status",
      "widget-calendar",
      "widget-executive-summary"
    ],
    preferences: ["theme", "language", "sidebarCollapsed", "dashboardLayout"],
    favorites: ["dashboard", "Executive Workspace", "AI Assistant", "Payments"],
    recentItems: ["Executive Workspace", "Finance Dashboard", "AI Assistant"],
    createdAt: "2026-06-29T08:00:00.000Z",
    updatedAt: now,
    metadata: { default: true, audience: "owner" }
  },
  {
    id: "workspace-finance",
    name: "Finance Workspace",
    description: "Cash, payments, purchases, invoices and financial monitoring.",
    type: "finance",
    ownerId: "user-admin",
    companyId: "company-hicotech",
    defaultRoute: "/paiements",
    modules: ["cash", "payments", "invoices", "purchases", "reports", "statistics", "pdf"],
    widgets: [
      "widget-cash-balance",
      "widget-payments-received",
      "widget-invoices-late",
      "widget-financial-distribution",
      "widget-sales-evolution"
    ],
    preferences: ["defaultCurrency", "showOverdueInvoices", "financeWidgetOrder", "printFormat", "showCompanyStamp"],
    favorites: ["Payments", "Monthly Sales Report", "Invoices", "Purchases"],
    recentItems: ["Finance Dashboard", "Invoice F-2026-154", "Purchase PO-2026-19", "Sales Report"],
    createdAt: "2026-06-29T08:05:00.000Z",
    updatedAt: now,
    metadata: { audience: "finance" }
  },
  {
    id: "workspace-sales",
    name: "Sales Workspace",
    description: "Clients, quotes, invoices and delivery follow-up.",
    type: "sales",
    ownerId: "user-admin",
    companyId: "company-hicotech",
    defaultRoute: "/devis",
    modules: ["clients", "documents", "quotes", "invoices", "delivery_notes", "payments", "products"],
    widgets: ["widget-quick-actions", "widget-top-clients", "widget-sales-evolution", "widget-invoices-late"],
    preferences: ["salesWidgetOrder", "defaultSalesModule"],
    favorites: ["Clients", "Invoices", "ABC SARL", "Search Clients"],
    recentItems: ["ABC SARL", "Invoice F-2026-154", "Search Clients"],
    createdAt: "2026-06-29T08:10:00.000Z",
    updatedAt: now,
    metadata: { audience: "sales" }
  },
  {
    id: "workspace-stock",
    name: "Stock Workspace",
    description: "Inventory, products, purchases and supplier operations.",
    type: "stock",
    ownerId: "user-admin",
    companyId: "company-hicotech",
    defaultRoute: "/stock",
    modules: ["products", "purchases", "suppliers", "delivery_notes", "reports", "statistics"],
    widgets: ["widget-stock-critical", "widget-top-products"],
    preferences: ["productsTableColumns"],
    favorites: ["Products", "Stock", "Purchases"],
    recentItems: ["Product Screen 86\"", "Inventory", "Supplier LG", "Stock Report"],
    createdAt: "2026-06-29T08:15:00.000Z",
    updatedAt: now,
    metadata: { audience: "operations" }
  },
  {
    id: "workspace-hr",
    name: "HR Workspace",
    description: "Human resources workspace for employees, contracts and payroll.",
    type: "hr",
    ownerId: "user-admin",
    companyId: "company-hicotech",
    defaultRoute: "/rh/employes",
    modules: ["employees", "contracts", "attendance", "absences", "leaves", "payroll", "advances", "hr_documents"],
    widgets: ["widget-calendar"],
    preferences: [],
    favorites: ["HR Dashboard"],
    recentItems: ["Employee Ahmed", "Contract Renewal"],
    createdAt: "2026-06-29T08:20:00.000Z",
    updatedAt: now,
    metadata: { audience: "hr" }
  },
  {
    id: "workspace-ai",
    name: "AI Workspace",
    description: "AI recommendations, assistant context and future automation workspace.",
    type: "ai",
    ownerId: "user-admin",
    companyId: "company-hicotech",
    defaultRoute: "/assistant-ia",
    modules: ["ai_assistant", "dashboard", "reports", "statistics"],
    widgets: ["widget-smart-insights", "widget-ai-recommendation"],
    preferences: ["aiRecommendationsEnabled", "aiTone", "searchShortcut", "commandPaletteRecentLimit"],
    favorites: ["AI Assistant"],
    recentItems: ["AI Assistant"],
    createdAt: "2026-06-29T08:25:00.000Z",
    updatedAt: now,
    metadata: { audience: "ai" }
  },
  {
    id: "workspace-system",
    name: "System Workspace",
    description: "Administration, settings, users and operational governance.",
    type: "system",
    ownerId: "user-admin",
    companyId: "company-hicotech",
    defaultRoute: "/parametres",
    modules: ["settings", "users", "pdf", "reports"],
    widgets: ["widget-system-status", "widget-security-health", "widget-audit-overview"],
    preferences: ["securityAlertsVisible"],
    favorites: ["Notifications", "Audit Logs"],
    recentItems: ["Notification Center"],
    createdAt: "2026-06-29T08:30:00.000Z",
    updatedAt: now,
    metadata: { audience: "admin" }
  }
];
