import type { DashboardContribution } from "./dashboard-contribution.types";

export const bosiacoDashboardContributions = Object.freeze([
  {
    id: "core.dashboard.hero",
    moduleId: "core.dashboard",
    widgetId: "dashboard.hero",
    title: "Hero exécutif",
    priority: 10,
    order: 10,
    zone: "hero",
    size: "full",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.hero",
    metadata: { section: "executive" }
  },
  {
    id: "core.dashboard.business-health",
    moduleId: "core.dashboard",
    widgetId: "dashboard.business-health",
    title: "Santé business",
    priority: 20,
    order: 20,
    zone: "summary",
    size: "full",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.business-health",
    metadata: { section: "business-health" }
  },
  {
    id: "crm.tasks.priority-center",
    moduleId: "crm.tasks",
    widgetId: "dashboard.priority-center",
    title: "Centre de priorité",
    priority: 30,
    order: 30,
    zone: "primary",
    size: "full",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.priority-center",
    metadata: { section: "daily-priorities" }
  },
  {
    id: "sales.quotes.performance",
    moduleId: "sales.quotes",
    widgetId: "dashboard.performance",
    title: "Performance commerciale",
    priority: 40,
    order: 40,
    zone: "primary",
    size: "full",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.performance",
    metadata: { section: "sales-performance" }
  },
  {
    id: "core.dashboard.recent-activity",
    moduleId: "core.dashboard",
    widgetId: "dashboard.recent-activity",
    title: "Changements récents",
    priority: 50,
    order: 50,
    zone: "secondary",
    size: "lg",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.recent-activity",
    metadata: { section: "recent-activity" }
  },
  {
    id: "core.dashboard.quick-actions",
    moduleId: "core.dashboard",
    widgetId: "dashboard.quick-actions",
    title: "Actions rapides",
    priority: 60,
    order: 60,
    zone: "secondary",
    size: "md",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.quick-actions",
    metadata: { section: "quick-actions" }
  },
  {
    id: "sales.orders.to-confirm",
    moduleId: "sales.orders",
    widgetId: "dashboard.sales.orders-to-confirm",
    title: "Commandes à confirmer",
    priority: 64,
    order: 64,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.sales.orders-to-confirm",
    metadata: { section: "sales-orders-to-confirm" }
  },
  {
    id: "sales.orders.reserved",
    moduleId: "sales.orders",
    widgetId: "dashboard.sales.orders-reserved",
    title: "Commandes réservées",
    priority: 65,
    order: 65,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.sales.orders-reserved",
    metadata: { section: "sales-orders-reserved" }
  },
  {
    id: "sales.orders.shortage",
    moduleId: "sales.orders",
    widgetId: "dashboard.sales.orders-shortage",
    title: "Commandes en rupture",
    priority: 66,
    order: 66,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.sales.orders-shortage",
    metadata: { section: "sales-orders-shortage" }
  },
  {
    id: "sales.orders.recent",
    moduleId: "sales.orders",
    widgetId: "dashboard.sales.orders-recent",
    title: "Commandes récentes",
    priority: 67,
    order: 67,
    zone: "footer",
    size: "lg",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.sales.orders-recent",
    metadata: { section: "sales-orders-recent" }
  },
  {
    id: "inventory.stock.low-stock",
    moduleId: "inventory.stock",
    widgetId: "dashboard.inventory.low-stock",
    title: "Stock faible",
    priority: 70,
    order: 70,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.inventory.low-stock",
    metadata: { section: "inventory-low-stock" }
  },
  {
    id: "sales.delivery-notes.to-prepare",
    moduleId: "sales.delivery-notes",
    widgetId: "dashboard.sales.deliveries-to-prepare",
    title: "Livraisons à préparer",
    priority: 68,
    order: 68,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.sales.deliveries-to-prepare",
    metadata: { section: "deliveries-to-prepare" }
  },
  {
    id: "sales.delivery-notes.partial",
    moduleId: "sales.delivery-notes",
    widgetId: "dashboard.sales.partial-deliveries",
    title: "Livraisons partielles",
    priority: 69,
    order: 69,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.sales.partial-deliveries",
    metadata: { section: "partial-deliveries" }
  },
  {
    id: "sales.delivery-notes.today",
    moduleId: "sales.delivery-notes",
    widgetId: "dashboard.sales.deliveries-today",
    title: "Livraisons du jour",
    priority: 69,
    order: 70,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.sales.deliveries-today",
    metadata: { section: "deliveries-today" }
  },
  {
    id: "sales.delivery-notes.orders-to-deliver",
    moduleId: "sales.delivery-notes",
    widgetId: "dashboard.sales.orders-to-deliver",
    title: "Commandes restant à livrer",
    priority: 69,
    order: 71,
    zone: "footer",
    size: "lg",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.sales.orders-to-deliver",
    metadata: { section: "orders-to-deliver" }
  },
  {
    id: "inventory.stock.available",
    moduleId: "inventory.stock",
    widgetId: "dashboard.inventory.available",
    title: "Stock disponible",
    priority: 71,
    order: 71,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.inventory.available",
    metadata: { section: "inventory-available" }
  },
  {
    id: "inventory.stock.movements",
    moduleId: "inventory.stock",
    widgetId: "dashboard.inventory.movements",
    title: "Mouvements récents",
    priority: 72,
    order: 72,
    zone: "footer",
    size: "lg",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.inventory.movements",
    metadata: { section: "inventory-movements" }
  },
  {
    id: "procurement.suppliers.active",
    moduleId: "procurement.suppliers",
    widgetId: "dashboard.procurement.active-suppliers",
    title: "Fournisseurs actifs",
    priority: 80,
    order: 80,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.procurement.active-suppliers",
    metadata: { section: "procurement-active-suppliers" }
  },
  {
    id: "procurement.purchase-orders.pending",
    moduleId: "procurement.purchase-orders",
    widgetId: "dashboard.procurement.pending-purchase-orders",
    title: "Commandes fournisseur en attente",
    priority: 81,
    order: 81,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.procurement.pending-purchase-orders",
    metadata: { section: "procurement-pending-purchase-orders" }
  },
  {
    id: "procurement.purchase-orders.recent",
    moduleId: "procurement.purchase-orders",
    widgetId: "dashboard.procurement.recent-purchases",
    title: "Achats récents",
    priority: 82,
    order: 82,
    zone: "footer",
    size: "lg",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.procurement.recent-purchases",
    metadata: { section: "procurement-recent-purchases" }
  },
  {
    id: "procurement.goods-receipts.today",
    moduleId: "procurement.goods-receipts",
    widgetId: "dashboard.procurement.goods-receipts-today",
    title: "Réceptions du jour",
    priority: 83,
    order: 83,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.procurement.goods-receipts-today",
    metadata: { section: "procurement-goods-receipts-today" }
  },
  {
    id: "procurement.goods-receipts.pending",
    moduleId: "procurement.goods-receipts",
    widgetId: "dashboard.procurement.pending-goods-receipts",
    title: "Réceptions à poster",
    priority: 84,
    order: 84,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.procurement.pending-goods-receipts",
    metadata: { section: "procurement-pending-goods-receipts" }
  },
  {
    id: "procurement.goods-receipts.received-today",
    moduleId: "procurement.goods-receipts",
    widgetId: "dashboard.procurement.received-today",
    title: "Quantités reçues aujourd'hui",
    priority: 85,
    order: 85,
    zone: "footer",
    size: "lg",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.procurement.received-today",
    metadata: { section: "procurement-received-today" }
  }
] satisfies readonly DashboardContribution[]);
