import type { DashboardContribution } from "./dashboard-contribution.types";

export const bosiacoDashboardContributions = Object.freeze([
  {
    id: "core.dashboard.hero",
    moduleId: "core.dashboard",
    widgetId: "dashboard.hero",
    title: "Hero exécutif",
    priority: 10,
    order: 10,
    zone: "hero",
    size: "full",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.hero",
    metadata: { section: "executive" }
  },
  {
    id: "core.dashboard.business-health",
    moduleId: "core.dashboard",
    widgetId: "dashboard.business-health",
    title: "Santé business",
    priority: 20,
    order: 20,
    zone: "summary",
    size: "full",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.business-health",
    metadata: { section: "business-health" }
  },
  {
    id: "crm.tasks.priority-center",
    moduleId: "crm.tasks",
    widgetId: "dashboard.priority-center",
    title: "Centre de priorité",
    priority: 30,
    order: 30,
    zone: "primary",
    size: "full",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.priority-center",
    metadata: { section: "daily-priorities" }
  },
  {
    id: "sales.quotes.performance",
    moduleId: "sales.quotes",
    widgetId: "dashboard.performance",
    title: "Performance commerciale",
    priority: 40,
    order: 40,
    zone: "primary",
    size: "full",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.performance",
    metadata: { section: "sales-performance" }
  },
  {
    id: "core.dashboard.recent-activity",
    moduleId: "core.dashboard",
    widgetId: "dashboard.recent-activity",
    title: "Changements récents",
    priority: 50,
    order: 50,
    zone: "secondary",
    size: "lg",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.recent-activity",
    metadata: { section: "recent-activity" }
  },
  {
    id: "core.dashboard.quick-actions",
    moduleId: "core.dashboard",
    widgetId: "dashboard.quick-actions",
    title: "Actions rapides",
    priority: 60,
    order: 60,
    zone: "secondary",
    size: "md",
    status: "alpha",
    defaultVisible: true,
    alphaReady: true,
    renderKey: "dashboard.quick-actions",
    metadata: { section: "quick-actions" }
  },
  {
    id: "inventory.stock.low-stock",
    moduleId: "inventory.stock",
    widgetId: "dashboard.inventory.low-stock",
    title: "Stock faible",
    priority: 70,
    order: 70,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.inventory.low-stock",
    metadata: { section: "inventory-low-stock" }
  },
  {
    id: "inventory.stock.available",
    moduleId: "inventory.stock",
    widgetId: "dashboard.inventory.available",
    title: "Stock disponible",
    priority: 71,
    order: 71,
    zone: "secondary",
    size: "md",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.inventory.available",
    metadata: { section: "inventory-available" }
  },
  {
    id: "inventory.stock.movements",
    moduleId: "inventory.stock",
    widgetId: "dashboard.inventory.movements",
    title: "Mouvements récents",
    priority: 72,
    order: 72,
    zone: "footer",
    size: "lg",
    status: "planned",
    defaultVisible: false,
    alphaReady: false,
    renderKey: "dashboard.inventory.movements",
    metadata: { section: "inventory-movements" }
  }
] satisfies readonly DashboardContribution[]);
