export const CORE_MODULE_ICONS = {
  dashboard: "LayoutDashboard",
  clients: "Users",
  suppliers: "Building2",
  products: "Boxes",
  documents: "FileText",
  quotes: "ClipboardList",
  invoices: "Receipt",
  delivery_notes: "Truck",
  purchases: "HandCoins",
  cash: "CircleDollarSign",
  payments: "WalletCards",
  employees: "ContactRound",
  contracts: "ScrollText",
  attendance: "CalendarCheck",
  absences: "CalendarX",
  leaves: "ShieldCheck",
  payroll: "Landmark",
  advances: "WalletCards",
  hr_documents: "FileArchive",
  reports: "PackageCheck",
  statistics: "BarChart3",
  pdf: "FileOutput",
  ai_assistant: "Bot",
  settings: "Settings",
  users: "UserCog"
} as const;
