import { registerWidget } from "./widgets.registry";
import type { WidgetInput } from "./widgets.types";

const dashboardPermission = [{ module: "dashboard", action: "view" as const }];
const reportPermission = [{ module: "reports", action: "view" as const }];
const financePermission = [{ module: "reports", action: "view" as const }];
const stockPermission = [{ module: "stock", action: "view" as const }];
const assistantPermission = [{ module: "assistant", action: "view" as const }];
const usersPermission = [{ module: "users", action: "view" as const }];

export const demoWidgets: WidgetInput[] = [
  {
    id: "widget-business-health",
    title: "Business Health",
    description: "Executive health overview for the company.",
    type: "kpi",
    category: "executive",
    moduleId: "dashboard",
    size: "wide",
    position: { area: "dashboard", row: 1, column: 1, order: 1 },
    pinned: true,
    favorite: true,
    refreshable: true,
    configurable: false,
    permissions: dashboardPermission,
    dataSource: { type: "static", source: "business_health" },
    createdAt: "2026-06-29T08:00:00.000Z",
    updatedAt: "2026-06-29T08:00:00.000Z"
  },
  {
    id: "widget-quick-actions",
    title: "Quick Actions",
    description: "Fast access to common business actions.",
    type: "list",
    category: "executive",
    moduleId: "dashboard",
    size: "wide",
    position: { area: "dashboard", row: 2, column: 1, order: 2 },
    pinned: true,
    refreshable: false,
    configurable: true,
    permissions: dashboardPermission,
    dataSource: { type: "registry", source: "core.commands.future" }
  },
  {
    id: "widget-smart-insights",
    title: "Smart Insights",
    description: "Executive insights generated from business activity.",
    type: "ai",
    category: "ai",
    moduleId: "ai_assistant",
    size: "wide",
    position: { area: "dashboard", row: 3, column: 1, order: 3 },
    favorite: true,
    refreshable: true,
    configurable: true,
    permissions: assistantPermission,
    dataSource: { type: "static", source: "smart_insights" }
  },
  {
    id: "widget-todays-priorities",
    title: "Today's Priorities",
    description: "Priority cards for the business owner.",
    type: "list",
    category: "executive",
    moduleId: "dashboard",
    size: "wide",
    position: { area: "dashboard", row: 4, column: 1, order: 4 },
    refreshable: true,
    configurable: true,
    permissions: dashboardPermission,
    dataSource: { type: "static", source: "todays_priorities" }
  },
  {
    id: "widget-recent-activity",
    title: "Recent Activity",
    description: "Latest business events from the Activity Engine.",
    type: "activity",
    category: "system",
    moduleId: "dashboard",
    size: "large",
    position: { area: "executive_workspace", row: 1, column: 1, order: 5 },
    refreshable: true,
    configurable: true,
    permissions: dashboardPermission,
    dataSource: { type: "service", source: "activityService.getRecent" }
  },
  {
    id: "widget-my-tasks",
    title: "My Tasks",
    description: "Personal task checklist foundation.",
    type: "task",
    category: "executive",
    moduleId: "dashboard",
    size: "medium",
    position: { area: "executive_workspace", row: 1, column: 2, order: 6 },
    refreshable: false,
    configurable: true,
    permissions: dashboardPermission,
    dataSource: { type: "static", source: "my_tasks" }
  },
  {
    id: "widget-system-status",
    title: "System Status",
    description: "System health status for operations.",
    type: "security",
    category: "system",
    moduleId: "settings",
    size: "medium",
    position: { area: "executive_workspace", row: 2, column: 2, order: 7 },
    refreshable: true,
    configurable: false,
    permissions: dashboardPermission,
    dataSource: { type: "static", source: "system_status" }
  },
  {
    id: "widget-sales-evolution",
    title: "Sales Evolution",
    description: "Sales trend over recent months.",
    type: "chart",
    category: "sales",
    moduleId: "statistics",
    size: "wide",
    position: { area: "analytics", row: 1, column: 1, order: 8 },
    refreshable: true,
    configurable: true,
    permissions: reportPermission,
    dataSource: { type: "static", source: "sales_evolution" }
  },
  {
    id: "widget-financial-distribution",
    title: "Financial Distribution",
    description: "Margin, purchases and expenses distribution.",
    type: "chart",
    category: "finance",
    moduleId: "statistics",
    size: "medium",
    position: { area: "analytics", row: 1, column: 2, order: 9 },
    refreshable: true,
    configurable: true,
    permissions: financePermission,
    dataSource: { type: "static", source: "financial_distribution" }
  },
  {
    id: "widget-top-clients",
    title: "Top Clients",
    description: "Highest value customers.",
    type: "list",
    category: "crm",
    moduleId: "clients",
    size: "medium",
    position: { area: "analytics", row: 2, column: 1, order: 10 },
    refreshable: true,
    configurable: true,
    permissions: [{ module: "clients", action: "view" }],
    dataSource: { type: "static", source: "top_clients" }
  },
  {
    id: "widget-top-products",
    title: "Top Products",
    description: "Best selling products.",
    type: "list",
    category: "stock",
    moduleId: "products",
    size: "medium",
    position: { area: "analytics", row: 2, column: 2, order: 11 },
    refreshable: true,
    configurable: true,
    permissions: stockPermission,
    dataSource: { type: "static", source: "top_products" }
  },
  {
    id: "widget-invoices-late",
    title: "Invoices Late",
    description: "Late invoices requiring attention.",
    type: "kpi",
    category: "finance",
    moduleId: "invoices",
    size: "small",
    position: { area: "dashboard", row: 5, column: 1, order: 12 },
    refreshable: true,
    configurable: true,
    permissions: [{ module: "invoices", action: "view" }],
    dataSource: { type: "static", source: "overdue_invoices" }
  },
  {
    id: "widget-stock-critical",
    title: "Stock Critical",
    description: "Products under minimum stock level.",
    type: "stock",
    category: "stock",
    moduleId: "products",
    size: "small",
    position: { area: "dashboard", row: 5, column: 2, order: 13 },
    refreshable: true,
    configurable: true,
    permissions: stockPermission,
    dataSource: { type: "static", source: "critical_stock" }
  },
  {
    id: "widget-cash-balance",
    title: "Cash Balance",
    description: "Estimated available cash balance.",
    type: "finance",
    category: "finance",
    moduleId: "cash",
    size: "small",
    position: { area: "dashboard", row: 5, column: 3, order: 14 },
    favorite: true,
    refreshable: true,
    configurable: true,
    permissions: [{ module: "cash", action: "view" }],
    dataSource: { type: "static", source: "cash_balance" }
  },
  {
    id: "widget-ai-recommendation",
    title: "AI Recommendation",
    description: "Recommended action generated by the AI platform.",
    type: "ai",
    category: "ai",
    moduleId: "ai_assistant",
    size: "medium",
    position: { area: "dashboard", row: 6, column: 1, order: 15 },
    refreshable: true,
    configurable: true,
    permissions: assistantPermission,
    dataSource: { type: "static", source: "ai_recommendation" }
  },
  {
    id: "widget-calendar",
    title: "Calendar",
    description: "Upcoming events and appointments.",
    type: "calendar",
    category: "executive",
    moduleId: "dashboard",
    size: "wide",
    position: { area: "executive_workspace", row: 3, column: 1, order: 16 },
    refreshable: true,
    configurable: true,
    permissions: dashboardPermission,
    dataSource: { type: "static", source: "calendar_events" }
  },
  {
    id: "widget-payments-received",
    title: "Payments Received",
    description: "Payments received today.",
    type: "finance",
    category: "finance",
    moduleId: "payments",
    size: "small",
    position: { area: "dashboard", row: 6, column: 2, order: 17 },
    refreshable: true,
    configurable: true,
    permissions: [{ module: "payments", action: "view" }],
    dataSource: { type: "static", source: "payments_received" }
  },
  {
    id: "widget-security-health",
    title: "Security Health",
    description: "Security overview for account and system events.",
    type: "security",
    category: "security",
    moduleId: "users",
    size: "medium",
    position: { area: "security", row: 1, column: 1, order: 18 },
    refreshable: true,
    configurable: true,
    permissions: usersPermission,
    dataSource: { type: "service", source: "notificationService.getByCategory.security" }
  },
  {
    id: "widget-audit-overview",
    title: "Audit Overview",
    description: "Audit activity overview for administrators.",
    type: "table",
    category: "security",
    moduleId: "users",
    size: "large",
    position: { area: "security", row: 2, column: 1, order: 19 },
    refreshable: true,
    configurable: true,
    permissions: usersPermission,
    dataSource: { type: "service", source: "activityService.getByCategory.administration" }
  },
  {
    id: "widget-executive-summary",
    title: "Executive Summary",
    description: "Compact business summary for the owner.",
    type: "kpi",
    category: "executive",
    moduleId: "dashboard",
    size: "full",
    position: { area: "dashboard", row: 0, column: 1, order: 0 },
    pinned: true,
    favorite: true,
    refreshable: true,
    configurable: true,
    permissions: dashboardPermission,
    dataSource: { type: "static", source: "executive_summary" }
  }
];

demoWidgets.forEach(registerWidget);
