import type { ModuleDescriptor } from "./module.types";

export const bosiacoModuleDescriptors = Object.freeze([
  {
    id: "core.dashboard",
    name: "Tableau de bord",
    shortName: "Dashboard",
    description: "Cockpit exécutif stable pour piloter les priorités quotidiennes.",
    category: "core",
    iconKey: "LayoutDashboard",
    route: "/dashboard",
    status: "alpha",
    version: "0.9.0",
    features: ["overview", "kpi", "priorities"],
    navigation: { label: "Tableau de bord", href: "/dashboard", iconKey: "LayoutDashboard", group: "Accueil", order: 10 },
    commandCenter: { navigationKeywords: ["dashboard", "tableau de bord", "accueil"] },
    dashboard: { dashboardSectionKey: "executive", widgetKeys: ["business-health", "priorities"], priority: 10 },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 10
  },
  {
    id: "core.settings",
    name: "Paramètres",
    description: "Paramètres locaux visibles pour l'administration Alpha.",
    category: "core",
    iconKey: "Settings",
    route: "/parametres",
    status: "alpha",
    version: "0.9.0",
    features: ["companyProfile", "numbering", "pdfSettings", "localUsers"],
    navigation: { label: "Paramètres", href: "/parametres", iconKey: "Settings", group: "Système", order: 90 },
    commandCenter: { navigationKeywords: ["paramètres", "configuration", "settings"] },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 20
  },
  {
    id: "platform.command-center",
    name: "Centre de commandes",
    description: "Entrée clavier centrale pour navigation, création rapide et recherche locale.",
    category: "platform",
    iconKey: "Command",
    status: "alpha",
    version: "0.9.0",
    features: ["navigation", "quickCreate", "recordSearch", "favorites", "recent"],
    commandCenter: { hidden: true },
    defaultEnabled: false,
    alphaReady: true,
    hidden: true,
    order: 30
  },
  {
    id: "platform.keyboard",
    name: "Raccourcis clavier",
    description: "Fondation clavier pour les surfaces Alpha.",
    category: "platform",
    iconKey: "Keyboard",
    status: "alpha",
    version: "0.9.0",
    features: ["commandK", "contextualCreate", "dialogSubmit", "escape"],
    defaultEnabled: false,
    alphaReady: true,
    hidden: true,
    order: 40
  },
  {
    id: "platform.persistence",
    name: "Persistance CRM/Sales",
    description: "Pont de persistance PostgreSQL pour les données CRM et Sales stables.",
    category: "platform",
    iconKey: "Database",
    status: "alpha",
    version: "0.9.0",
    features: ["tenantScope", "crmSalesBridge", "hydration"],
    defaultEnabled: false,
    alphaReady: true,
    hidden: true,
    order: 50
  },
  {
    id: "crm.overview",
    name: "CRM",
    description: "Vue d'ensemble relationnelle des sociétés, contacts et activités.",
    category: "crm",
    iconKey: "ContactRound",
    route: "/crm",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["crm.companies", "crm.contacts"],
    optionalDependencies: ["crm.meetings", "crm.tasks", "crm.notes"],
    features: ["overview", "activitySummary", "quickActions"],
    navigation: { label: "Vue d'ensemble", href: "/crm", iconKey: "ContactRound", group: "CRM", order: 100 },
    commandCenter: { navigationKeywords: ["crm", "relation client", "sociétés", "contacts"] },
    dashboard: { dashboardSectionKey: "crm", widgetKeys: ["crm-overview"], priority: 20 },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 100
  },
  {
    id: "crm.companies",
    name: "Sociétés",
    description: "Comptes commerciaux company-centric avec détails, contacts et contexte Sales.",
    category: "crm",
    iconKey: "Building2",
    route: "/crm/companies",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["platform.persistence"],
    features: ["create", "edit", "archive", "favorite", "contacts", "quotes", "invoices", "payments"],
    navigation: { label: "Sociétés", href: "/crm/companies", iconKey: "Building2", group: "CRM", order: 110 },
    commandCenter: { navigationKeywords: ["sociétés", "societes", "entreprises", "companies"], quickCreateKeys: ["quick-create.company"], recordSearchKeys: ["company"] },
    dashboard: { dashboardSectionKey: "crm", widgetKeys: ["companies"], priority: 21 },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 110
  },
  {
    id: "crm.contacts",
    name: "Contacts",
    description: "Répertoire global des contacts reliés aux sociétés.",
    category: "crm",
    iconKey: "ContactRound",
    route: "/crm/contacts",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["crm.companies", "platform.persistence"],
    features: ["create", "edit", "archive", "favorite", "meetings", "tasks", "notes"],
    navigation: { label: "Contacts", href: "/crm/contacts", iconKey: "ContactRound", group: "CRM", order: 120 },
    commandCenter: { navigationKeywords: ["contacts", "personnes"], quickCreateKeys: ["quick-create.contact"], recordSearchKeys: ["contact"] },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 120
  },
  {
    id: "crm.meetings",
    name: "Réunions",
    description: "Réunions CRM persistées et reliées aux sociétés et contacts.",
    category: "crm",
    iconKey: "CalendarCheck",
    route: "/crm/meetings",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["crm.companies", "platform.persistence"],
    optionalDependencies: ["crm.contacts"],
    features: ["create", "edit", "cancel", "companyContext", "contactContext"],
    navigation: { label: "Réunions", href: "/crm/meetings", iconKey: "CalendarCheck", group: "CRM", order: 130 },
    commandCenter: { navigationKeywords: ["réunions", "reunions", "meetings"], recordSearchKeys: ["meeting"] },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 130
  },
  {
    id: "crm.tasks",
    name: "Tâches",
    description: "Actions de suivi CRM persistées.",
    category: "crm",
    iconKey: "ScrollText",
    route: "/crm/tasks",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["crm.companies", "platform.persistence"],
    optionalDependencies: ["crm.contacts"],
    features: ["create", "edit", "complete", "companyContext", "contactContext"],
    navigation: { label: "Tâches", href: "/crm/tasks", iconKey: "ScrollText", group: "CRM", order: 140 },
    commandCenter: { navigationKeywords: ["tâches", "taches", "tasks"], recordSearchKeys: ["task"] },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 140
  },
  {
    id: "crm.notes",
    name: "Notes",
    description: "Notes CRM persistées pour sociétés et contacts.",
    category: "crm",
    iconKey: "FileText",
    route: "/crm/notes",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["crm.companies", "platform.persistence"],
    optionalDependencies: ["crm.contacts"],
    features: ["create", "edit", "archive", "companyContext", "contactContext"],
    navigation: { label: "Notes", href: "/crm/notes", iconKey: "FileText", group: "CRM", order: 150 },
    commandCenter: { navigationKeywords: ["notes"], recordSearchKeys: ["note"] },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 150
  },
  {
    id: "sales.quotes",
    name: "Devis",
    description: "Création et suivi des devis avec lignes commerciales et PDF.",
    category: "sales",
    iconKey: "FileText",
    route: "/sales/quotes",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["crm.companies", "crm.contacts", "platform.persistence"],
    features: ["create", "edit", "pdf", "convertToInvoice", "lineItems"],
    navigation: { label: "Devis", href: "/sales/quotes", iconKey: "FileText", group: "Ventes", order: 200 },
    commandCenter: { navigationKeywords: ["devis", "quotes"], quickCreateKeys: ["quick-create.quote"], recordSearchKeys: ["quote"] },
    dashboard: { dashboardSectionKey: "sales", widgetKeys: ["quotes"], priority: 30 },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 200
  },
  {
    id: "sales.invoices",
    name: "Factures",
    description: "Factures avec lignes, contexte CRM et PDF.",
    category: "sales",
    iconKey: "Receipt",
    route: "/sales/invoices",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["sales.quotes", "crm.companies", "platform.persistence"],
    optionalDependencies: ["crm.contacts"],
    features: ["create", "edit", "pdf", "lineItems", "sourceQuote"],
    navigation: { label: "Factures", href: "/sales/invoices", iconKey: "Receipt", group: "Ventes", order: 210 },
    commandCenter: { navigationKeywords: ["factures", "invoices"], quickCreateKeys: ["quick-create.invoice"], recordSearchKeys: ["invoice"] },
    dashboard: { dashboardSectionKey: "sales", widgetKeys: ["invoices"], priority: 31 },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 210
  },
  {
    id: "sales.payments",
    name: "Paiements",
    description: "Suivi des paiements et encaissements reliés aux factures.",
    category: "sales",
    iconKey: "WalletCards",
    route: "/sales/payments",
    status: "alpha",
    version: "0.9.0",
    dependencies: ["sales.invoices", "crm.companies", "platform.persistence"],
    features: ["recordPayment", "list", "details", "archive"],
    navigation: { label: "Paiements", href: "/sales/payments", iconKey: "WalletCards", group: "Ventes", order: 220 },
    commandCenter: { navigationKeywords: ["paiements", "payments", "encaissements"], recordSearchKeys: ["payment"] },
    dashboard: { dashboardSectionKey: "sales", widgetKeys: ["payments"], priority: 32 },
    defaultEnabled: true,
    alphaReady: true,
    hidden: false,
    order: 220
  },
  {
    id: "crm.opportunities",
    name: "Opportunités",
    description: "Pipeline commercial futur, masqué tant que la persistance n'est pas prête.",
    category: "crm",
    iconKey: "KanbanSquare",
    route: "/crm/opportunities",
    status: "hidden",
    version: "0.9.0",
    dependencies: ["crm.companies"],
    optionalDependencies: ["crm.contacts"],
    features: ["pipeline", "stages"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 300
  },
  {
    id: "sales.products",
    name: "Catalogue produits",
    description: "Catalogue produit canonique pour les futurs modules ventes, stock, achats, livraison et reporting.",
    category: "sales",
    iconKey: "PackageCheck",
    route: "/sales/products",
    status: "planned",
    version: "0.2.0",
    dependencies: ["platform.persistence"],
    optionalDependencies: ["inventory.stock", "purchasing.orders"],
    features: ["catalog", "sku", "barcode", "categories", "units", "pricing", "vatDefaults", "archive", "restore"],
    navigation: { label: "Produits", href: "/sales/products", iconKey: "PackageCheck", group: "Stock", order: 400 },
    commandCenter: { navigationKeywords: ["produits", "catalogue", "sku", "articles"], recordSearchKeys: ["product"] },
    hidden: false,
    defaultEnabled: false,
    alphaReady: false,
    order: 310
  },
  {
    id: "inventory.stock",
    name: "Stock",
    description: "Domaine inventaire futur basé sur le catalogue produit canonique.",
    category: "inventory",
    iconKey: "Boxes",
    route: "/inventory",
    status: "planned",
    version: "0.3.0",
    dependencies: ["sales.products", "platform.persistence"],
    features: ["warehouses", "balances", "movements", "posting", "reservations", "availability"],
    navigation: { label: "Stock", href: "/inventory", iconKey: "Boxes", group: "Stock", order: 410, searchKeywords: ["inventaire", "entrepôts", "mouvements", "stock"] },
    commandCenter: { navigationKeywords: ["stock", "inventaire", "entrepôts", "mouvements"], recordSearchKeys: ["warehouse"] },
    dashboard: { dashboardSectionKey: "inventory", widgetKeys: ["stock-low", "stock-available", "stock-movements"], priority: 40 },
    hidden: false,
    defaultEnabled: false,
    alphaReady: false,
    order: 320
  },
  {
    id: "purchasing.orders",
    name: "Achats",
    description: "Commandes et factures fournisseurs futures.",
    category: "purchasing",
    iconKey: "HandCoins",
    route: "/achats",
    status: "planned",
    version: "0.1.0",
    optionalDependencies: ["purchasing.suppliers"],
    features: ["orders", "supplierInvoices"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 330
  },
  {
    id: "purchasing.suppliers",
    name: "Fournisseurs",
    description: "Répertoire fournisseurs futur.",
    category: "purchasing",
    iconKey: "Building2",
    route: "/fournisseurs",
    status: "planned",
    version: "0.1.0",
    features: ["supplierDirectory"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 340
  },
  {
    id: "finance.cash",
    name: "Caisse",
    description: "Journal de caisse futur.",
    category: "finance",
    iconKey: "CircleDollarSign",
    route: "/caisse",
    status: "planned",
    version: "0.1.0",
    features: ["cashJournal"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 350
  },
  {
    id: "finance.reports",
    name: "Statistiques",
    description: "Reporting financier futur.",
    category: "finance",
    iconKey: "BarChart3",
    route: "/statistiques",
    status: "planned",
    version: "0.1.0",
    features: ["reports", "exports"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 360
  },
  {
    id: "hr.employees",
    name: "Ressources humaines",
    description: "Fondation RH future.",
    category: "hr",
    iconKey: "Users",
    route: "/rh",
    status: "planned",
    version: "0.1.0",
    features: ["employees", "leaves", "payroll"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 370
  },
  {
    id: "platform.notifications",
    name: "Notifications",
    description: "Centre de notifications futur.",
    category: "platform",
    iconKey: "Bell",
    status: "planned",
    version: "0.1.0",
    features: ["notificationCenter"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 380
  },
  {
    id: "platform.audit",
    name: "Audit",
    description: "Journal d'audit futur pour gouvernance et conformité.",
    category: "platform",
    iconKey: "ShieldCheck",
    status: "planned",
    version: "0.1.0",
    features: ["auditLog"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 390
  },
  {
    id: "ai.assistant",
    name: "Assistant IA",
    description: "Assistant métier futur, permission-aware.",
    category: "ai",
    iconKey: "Bot",
    route: "/assistant-ia",
    status: "planned",
    version: "0.1.0",
    features: ["assistant", "recommendations"],
    hidden: true,
    defaultEnabled: false,
    alphaReady: false,
    order: 400
  }
] satisfies readonly ModuleDescriptor[]);

export const bosiacoModuleRegistryVersion = "SPR-401";
