import type { CompanyId, UserId } from "../../companies/company.types";
import { CRM_COMPANIES_USER_ID, CRM_COMPANIES_WORKSPACE_ID } from "../../companies/ui/companies.seed";
import type { Contact, ContactId } from "../contact.types";

export const CRM_CONTACTS_USER_ID = CRM_COMPANIES_USER_ID as UserId;
export const CRM_CONTACTS_WORKSPACE_ID = CRM_COMPANIES_WORKSPACE_ID;

export const crmContactSeed = Object.freeze([
  {
    id: "contact-sara-amrani" as ContactId,
    workspaceId: CRM_CONTACTS_WORKSPACE_ID,
    companyId: "company-al-hikma" as CompanyId,
    firstName: "Sara",
    lastName: "Amrani",
    fullName: "Sara Amrani",
    jobTitle: "Directrice achats",
    department: "Achats",
    email: "sara.amrani@alhikma.ma",
    mobilePhone: "0661 10 20 30",
    officePhone: "0522 10 20 30",
    preferredLanguage: "fr",
    timezone: "Africa/Casablanca",
    status: "active",
    role: "decision_maker",
    isPrimaryContact: true,
    isDecisionMaker: true,
    linkedin: "https://linkedin.com/in/sara-amrani",
    notes: "Contact principal pour les projets éducation.",
    tags: Object.freeze(["vip", "achats"]),
    ownerId: CRM_CONTACTS_USER_ID,
    createdAt: "2026-06-12T09:00:00.000Z",
    updatedAt: "2026-06-29T10:30:00.000Z",
    createdBy: CRM_CONTACTS_USER_ID,
    updatedBy: CRM_CONTACTS_USER_ID
  },
  {
    id: "contact-youssef-hakimi" as ContactId,
    workspaceId: CRM_CONTACTS_WORKSPACE_ID,
    companyId: "company-al-hikma" as CompanyId,
    firstName: "Youssef",
    lastName: "Hakimi",
    fullName: "Youssef Hakimi",
    jobTitle: "Responsable IT",
    department: "IT",
    email: "youssef.hakimi@alhikma.ma",
    mobilePhone: "0661 40 50 60",
    preferredLanguage: "fr",
    timezone: "Africa/Casablanca",
    status: "active",
    role: "technical",
    isPrimaryContact: false,
    isDecisionMaker: false,
    tags: Object.freeze(["it"]),
    ownerId: CRM_CONTACTS_USER_ID,
    createdAt: "2026-06-13T11:15:00.000Z",
    updatedAt: "2026-06-28T15:20:00.000Z",
    createdBy: CRM_CONTACTS_USER_ID
  },
  {
    id: "contact-nadia-bennani" as ContactId,
    workspaceId: CRM_CONTACTS_WORKSPACE_ID,
    companyId: "company-ibn-sina" as CompanyId,
    firstName: "Nadia",
    lastName: "Bennani",
    fullName: "Nadia Bennani",
    jobTitle: "Directrice administrative",
    department: "Administration",
    email: "nadia.bennani@ibnsina.ma",
    mobilePhone: "0678 12 34 56",
    preferredLanguage: "fr",
    timezone: "Africa/Casablanca",
    status: "active",
    role: "primary",
    isPrimaryContact: true,
    isDecisionMaker: false,
    tags: Object.freeze(["administration"]),
    ownerId: CRM_CONTACTS_USER_ID,
    createdAt: "2026-06-15T08:45:00.000Z",
    updatedAt: "2026-06-24T12:05:00.000Z",
    createdBy: CRM_CONTACTS_USER_ID
  },
  {
    id: "contact-mehdi-atlas" as ContactId,
    workspaceId: CRM_CONTACTS_WORKSPACE_ID,
    companyId: "company-atlas" as CompanyId,
    firstName: "Mehdi",
    lastName: "El Atlas",
    fullName: "Mehdi El Atlas",
    jobTitle: "Responsable opérations",
    department: "Operations",
    email: "operations@atlas.ma",
    mobilePhone: "0662 33 44 55",
    preferredLanguage: "fr",
    timezone: "Africa/Casablanca",
    status: "active",
    role: "operations",
    isPrimaryContact: true,
    isDecisionMaker: true,
    tags: Object.freeze(["industrie", "operations"]),
    ownerId: CRM_CONTACTS_USER_ID,
    createdAt: "2026-06-18T13:20:00.000Z",
    updatedAt: "2026-06-27T09:10:00.000Z",
    createdBy: CRM_CONTACTS_USER_ID
  }
] satisfies readonly Contact[]);
