import type { EditionProfile } from "./edition.types";

export const alphaCrmSalesEditionProfile = Object.freeze({
  id: "alpha.crm-sales",
  name: "BOSIACO Alpha CRM & Sales",
  shortName: "Alpha CRM & Sales",
  description: "Edition Alpha active combinant le cockpit exécutif, le CRM company-centric et les workflows Sales stabilisés.",
  status: "alpha",
  version: "0.9.0",
  targetAudience: "Equipes dirigeantes et commerciales qui testent le périmètre Alpha stable.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: true,
  allowPreviewModules: false,
  allowPlannedModules: false,
  allowDeprecatedModules: false,
  defaultForEnvironment: true,
  commercial: false,
  order: 10,
  enabledModuleIds: Object.freeze([
    "core.dashboard",
    "core.settings",
    "crm.overview",
    "crm.companies",
    "crm.contacts",
    "crm.meetings",
    "crm.tasks",
    "crm.notes",
    "sales.quotes",
    "sales.invoices",
    "sales.payments"
  ]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["alpha", "crm", "sales"]),
  notes: Object.freeze(["Current runtime default. Must preserve the visible Alpha product exactly."]),
  futureLicenseKey: "edition.alpha.crm-sales",
  futurePlanCode: "ALPHA_CRM_SALES"
} satisfies EditionProfile);

export const basicEditionProfile = Object.freeze({
  id: "basic",
  name: "BOSIACO Basic",
  shortName: "Basic",
  description: "Future lightweight edition focused on dashboard, settings, companies and contacts.",
  status: "preview",
  version: "0.1.0",
  targetAudience: "Small teams that need a simple company and contact directory.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: true,
  allowPreviewModules: false,
  allowPlannedModules: false,
  defaultForEnvironment: false,
  commercial: true,
  order: 20,
  enabledModuleIds: Object.freeze(["core.dashboard", "core.settings", "crm.companies", "crm.contacts"]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["commercial", "starter"]),
  futureLicenseKey: "edition.basic",
  futurePlanCode: "BASIC"
} satisfies EditionProfile);

export const crmEditionProfile = Object.freeze({
  id: "crm",
  name: "BOSIACO CRM",
  shortName: "CRM",
  description: "Future CRM-focused edition for relationship management, company context and follow-up activity.",
  status: "preview",
  version: "0.1.0",
  targetAudience: "Commercial teams that manage companies, contacts, meetings, tasks and notes.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: true,
  allowPreviewModules: false,
  allowPlannedModules: false,
  defaultForEnvironment: false,
  commercial: true,
  order: 30,
  enabledModuleIds: Object.freeze([
    "core.dashboard",
    "core.settings",
    "crm.overview",
    "crm.companies",
    "crm.contacts",
    "crm.meetings",
    "crm.tasks",
    "crm.notes"
  ]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["commercial", "crm"]),
  notes: Object.freeze(["Future opportunities can join this profile only after persistence is stable."]),
  futureLicenseKey: "edition.crm",
  futurePlanCode: "CRM"
} satisfies EditionProfile);

export const salesEditionProfile = Object.freeze({
  id: "sales",
  name: "BOSIACO Sales",
  shortName: "Sales",
  description: "Future commercial edition combining CRM foundation with quotes, invoices and payments.",
  status: "preview",
  version: "0.1.0",
  targetAudience: "Teams that need company-centric sales documents and payment follow-up.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: true,
  allowPreviewModules: false,
  allowPlannedModules: false,
  defaultForEnvironment: false,
  commercial: true,
  order: 40,
  enabledModuleIds: Object.freeze([
    "core.dashboard",
    "core.settings",
    "crm.overview",
    "crm.companies",
    "crm.contacts",
    "sales.quotes",
    "sales.invoices",
    "sales.payments"
  ]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["commercial", "sales"]),
  futureLicenseKey: "edition.sales",
  futurePlanCode: "SALES"
} satisfies EditionProfile);

export const inventoryEditionProfile = Object.freeze({
  id: "inventory",
  name: "BOSIACO Inventory",
  shortName: "Inventory",
  description: "Planned inventory edition metadata for product catalog and stock workflows.",
  status: "planned",
  version: "0.1.0",
  targetAudience: "Businesses that will manage stock, warehouses and inventory movements.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: true,
  allowPreviewModules: false,
  allowPlannedModules: true,
  defaultForEnvironment: false,
  commercial: true,
  order: 50,
  enabledModuleIds: Object.freeze(["core.dashboard", "core.settings", "sales.products", "inventory.stock"]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["commercial", "planned", "inventory"]),
  notes: Object.freeze(["Metadata only. This edition is not selectable in the Alpha runtime."]),
  futureLicenseKey: "edition.inventory",
  futurePlanCode: "INVENTORY"
} satisfies EditionProfile);

export const purchasingEditionProfile = Object.freeze({
  id: "purchasing",
  name: "BOSIACO Purchasing",
  shortName: "Purchasing",
  description: "Planned purchasing edition metadata for suppliers, requests and purchase orders.",
  status: "planned",
  version: "0.1.0",
  targetAudience: "Businesses that will manage suppliers and purchasing flows.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: true,
  allowPreviewModules: false,
  allowPlannedModules: true,
  defaultForEnvironment: false,
  commercial: true,
  order: 60,
  enabledModuleIds: Object.freeze(["core.dashboard", "core.settings", "purchasing.suppliers", "purchasing.orders"]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["commercial", "planned", "purchasing"]),
  notes: Object.freeze(["Metadata only. This edition is not selectable in the Alpha runtime."]),
  futureLicenseKey: "edition.purchasing",
  futurePlanCode: "PURCHASING"
} satisfies EditionProfile);

export const hrEditionProfile = Object.freeze({
  id: "hr",
  name: "BOSIACO HR",
  shortName: "HR",
  description: "Planned HR edition metadata for employees, contracts, leave and payroll.",
  status: "planned",
  version: "0.1.0",
  targetAudience: "Businesses that will manage employee administration from BOSIACO.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: true,
  allowPreviewModules: false,
  allowPlannedModules: true,
  defaultForEnvironment: false,
  commercial: true,
  order: 70,
  enabledModuleIds: Object.freeze(["core.dashboard", "core.settings", "hr.employees"]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["commercial", "planned", "hr"]),
  notes: Object.freeze(["Metadata only. This edition is not selectable in the Alpha runtime."]),
  futureLicenseKey: "edition.hr",
  futurePlanCode: "HR"
} satisfies EditionProfile);

export const enterpriseEditionProfile = Object.freeze({
  id: "enterprise",
  name: "BOSIACO Enterprise",
  shortName: "Enterprise",
  description: "Future enterprise edition metadata for all stable production modules from one codebase.",
  status: "preview",
  version: "0.1.0",
  targetAudience: "Organizations that need the complete stable BOSIACO platform once modules mature.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: true,
  allowPreviewModules: false,
  allowPlannedModules: false,
  defaultForEnvironment: false,
  commercial: true,
  order: 80,
  enabledModuleIds: Object.freeze([
    "core.dashboard",
    "core.settings",
    "crm.overview",
    "crm.companies",
    "crm.contacts",
    "crm.meetings",
    "crm.tasks",
    "crm.notes",
    "sales.quotes",
    "sales.invoices",
    "sales.payments"
  ]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["commercial", "enterprise"]),
  notes: Object.freeze(["Planned and hidden modules stay excluded until they become stable."]),
  futureLicenseKey: "edition.enterprise",
  futurePlanCode: "ENTERPRISE"
} satisfies EditionProfile);

export const customEditionProfile = Object.freeze({
  id: "custom",
  name: "BOSIACO Custom",
  shortName: "Custom",
  description: "Internal foundation profile for future declarative module selections.",
  status: "internal",
  version: "0.1.0",
  targetAudience: "Future tenant-specific edition builder and implementation partners.",
  includeDefaults: false,
  strictDependencies: true,
  allowHiddenModules: false,
  allowPreviewModules: false,
  allowPlannedModules: false,
  defaultForEnvironment: false,
  commercial: false,
  order: 90,
  enabledModuleIds: Object.freeze([]),
  disabledModuleIds: Object.freeze([]),
  tags: Object.freeze(["internal", "custom"]),
  notes: Object.freeze(["Foundation only. No runtime selector, tenant override or persistence in SPR-403."]),
  futureLicenseKey: "edition.custom",
  futurePlanCode: "CUSTOM"
} satisfies EditionProfile);

export const bosiacoEditionProfiles = Object.freeze([
  alphaCrmSalesEditionProfile,
  basicEditionProfile,
  crmEditionProfile,
  salesEditionProfile,
  inventoryEditionProfile,
  purchasingEditionProfile,
  hrEditionProfile,
  enterpriseEditionProfile,
  customEditionProfile
] satisfies readonly EditionProfile[]);
