export * from "./crm.capabilities";
export * from "./crm.constants";
export * from "./crm.manifest";
export * from "./crm.module";
export * from "./crm.navigation";
export * from "./crm.permissions";
export * from "./crm.routes";
export * from "./crm.types";
export * as CrmActivities from "./activities";
export * as CrmCompanies from "./companies";
export * as CrmContacts from "./contacts";
export * as CrmCustomers from "./customers";
export * as CrmShared from "./shared";
