import type { Company, CompanyId, UserId, WorkspaceId } from "../company.types";

export const CRM_COMPANIES_WORKSPACE_ID = "workspace-hicopilot" as WorkspaceId;
export const CRM_COMPANIES_USER_ID = "user-admin" as UserId;

export const crmCompanySeed = Object.freeze([
  {
    id: "company-al-hikma" as CompanyId,
    workspaceId: CRM_COMPANIES_WORKSPACE_ID,
    legalName: "Ecole Al Hikma SARL",
    displayName: "Ecole Al Hikma",
    registrationNumber: "RC-98765",
    taxNumber: "IF-12345678",
    industry: "education",
    website: "https://alhikma.ma",
    email: "contact@alhikma.ma",
    phone: "0661 22 33 44",
    address: "45, Rue des Ecoles",
    city: "Casablanca",
    country: "Maroc",
    status: "active",
    tags: Object.freeze(["education", "vip"]),
    notes: "Compte stratégique du segment éducation.",
    ownerId: CRM_COMPANIES_USER_ID,
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: "2026-06-28T11:20:00.000Z",
    createdBy: CRM_COMPANIES_USER_ID,
    updatedBy: CRM_COMPANIES_USER_ID
  },
  {
    id: "company-ibn-sina" as CompanyId,
    workspaceId: CRM_COMPANIES_WORKSPACE_ID,
    legalName: "Lycee Ibn Sina",
    displayName: "Lycee Ibn Sina",
    registrationNumber: "RC-87654",
    taxNumber: "IF-23456789",
    industry: "education",
    website: "https://ibnsina.ma",
    email: "administration@ibnsina.ma",
    phone: "0678 11 22 33",
    address: "78, Bd Hassan II",
    city: "Rabat",
    country: "Maroc",
    status: "lead",
    tags: Object.freeze(["education", "devis"]),
    ownerId: CRM_COMPANIES_USER_ID,
    createdAt: "2026-06-04T10:15:00.000Z",
    updatedAt: "2026-06-27T16:40:00.000Z",
    createdBy: CRM_COMPANIES_USER_ID
  },
  {
    id: "company-atlas" as CompanyId,
    workspaceId: CRM_COMPANIES_WORKSPACE_ID,
    legalName: "Entreprise Atlas",
    displayName: "Entreprise Atlas",
    registrationNumber: "RC-76543",
    taxNumber: "IF-34567890",
    industry: "manufacturing",
    email: "achats@atlas.ma",
    phone: "0662 33 44 55",
    address: "12, Zone Industrielle",
    city: "Casablanca",
    country: "Maroc",
    status: "active",
    tags: Object.freeze(["industrie", "relance"]),
    notes: "Relations futures: factures, commandes et projets.",
    ownerId: CRM_COMPANIES_USER_ID,
    createdAt: "2026-06-07T08:30:00.000Z",
    updatedAt: "2026-06-26T14:05:00.000Z",
    createdBy: CRM_COMPANIES_USER_ID
  },
  {
    id: "company-lumiere" as CompanyId,
    workspaceId: CRM_COMPANIES_WORKSPACE_ID,
    legalName: "Clinique Lumiere",
    displayName: "Clinique Lumiere",
    registrationNumber: "RC-65432",
    taxNumber: "IF-45678901",
    industry: "healthcare",
    website: "https://cliniquelumiere.ma",
    email: "direction@cliniquelumiere.ma",
    phone: "0663 44 55 66",
    address: "9, Avenue Mohammed VI",
    city: "Marrakech",
    country: "Maroc",
    status: "active",
    tags: Object.freeze(["sante", "premium"]),
    ownerId: CRM_COMPANIES_USER_ID,
    createdAt: "2026-06-09T12:00:00.000Z",
    updatedAt: "2026-06-25T09:45:00.000Z",
    createdBy: CRM_COMPANIES_USER_ID
  },
  {
    id: "company-noor" as CompanyId,
    workspaceId: CRM_COMPANIES_WORKSPACE_ID,
    legalName: "Groupe Noor",
    displayName: "Groupe Noor",
    registrationNumber: "RC-54321",
    taxNumber: "IF-56789012",
    industry: "finance",
    email: "finance@groupenoor.ma",
    phone: "0664 55 66 77",
    city: "Tanger",
    country: "Maroc",
    status: "inactive",
    tags: Object.freeze(["finance"]),
    ownerId: CRM_COMPANIES_USER_ID,
    createdAt: "2026-06-12T15:10:00.000Z",
    updatedAt: "2026-06-21T13:25:00.000Z",
    createdBy: CRM_COMPANIES_USER_ID
  }
] satisfies readonly Company[]);

